#!/bin/bash

PACKAGES_TO_DISABLE=(
    # adb shell pm list packages -d -s | sed 's/package://g' | sort
    android.autoinstalls.config.samsung
    com.android.chrome
    com.android.dreams.basic
    com.android.dreams.phototable
    com.android.hotwordenrollment.xgoogle
    com.diotek.sec.lookup.dictionary
    com.facebook.appmanager
    com.facebook.services
    com.facebook.system
    com.google.android.adservices.api
    com.google.android.apps.accessibility.voiceaccess
    com.google.android.apps.aiwallpapers
    com.google.android.apps.googleassistant
    com.google.android.apps.messaging
    com.google.android.apps.restore
    com.google.android.apps.tachyon
    com.google.android.as
    com.google.android.feedback
    com.google.android.gm
    com.google.android.gms.supervision
    com.google.android.googlequicksearchbox
    com.google.android.printservice.recommendation
    com.google.android.setupwizard
    com.google.android.youtube
    com.google.audio.hearing.visualization.accessibility.scribe
    com.knox.vpn.proxyhandler
    com.microsoft.skydrive
    com.samsung.SMT.lang_en_us_l03
    com.samsung.SMT.lang_ru_ru_f00
    com.samsung.android.app.omcagent
    com.samsung.android.app.updatecenter
    com.samsung.android.appseparation
    com.samsung.android.ardrawing
    com.samsung.android.aremoji
    com.samsung.android.aremojieditor
    com.samsung.android.authfw
    com.samsung.android.bbc.bbcagent
    com.samsung.android.bixby.agent
    com.samsung.android.carkey
    com.samsung.android.dkey
    com.samsung.android.dqagent
    com.samsung.android.forest
    com.samsung.android.game.gamehome
    com.samsung.android.game.gametools
    com.samsung.android.game.gos
    com.samsung.android.ipsgeofence
    com.samsung.android.knox.analytics.uploader
    com.samsung.android.knox.attestation
    com.samsung.android.knox.containercore
    com.samsung.android.knox.kpecore
    com.samsung.android.knox.pushmanager
    com.samsung.android.knox.zt.framework
    com.samsung.android.mapsagent
    com.samsung.android.mcfds
    com.samsung.android.peripheral.framework
    com.samsung.android.rampart
    com.samsung.android.samsungpass
    com.samsung.android.samsungpassautofill
    com.samsung.android.smartsuggestions
    com.samsung.android.themestore
    com.samsung.android.visionintelligence
    com.samsung.cmfa.AuthTouch
    com.samsung.knox.securefolder
    com.sec.android.app.billing
    com.sec.android.app.dexonpc
    com.sec.android.app.vepreload
    com.sec.android.easyMover
    com.sec.android.mimage.avatarstickers
    com.sec.android.soagent
    com.sec.android.widgetapp.webmanual
    com.swiftkey.swiftkeyconfigurator
    com.touchtype.swiftkey
    com.wssyncmldm
)

for PACKAGE in "${PACKAGES_TO_DISABLE[@]}"; do
    adb shell pm disable-user --user 0 "$PACKAGE"
done
